### PR TITLE
Plagiarism 

### PR DESCRIPTION
**Pull request by TrevorAnimates**
U copied and pasted demos engine lmao

### CODE REVIEW

**Comment by SonicProYT** [comment]
im taking this down right now

**Comment by SonicProYT** [comment]
BRO I MEANT THE NEOSTUDIOS FORK 
NOT YOUR PULL REQUEST

**Comment by DEMOLITIONDON96** [comment]
Holy fucking shit guys, how do you not see that NeoStudios the thief here, not SonicProYT, absolute bruh moment lmao

**Comment by TrevorAnimates** [comment]
25217480-055D-45DA-B483-BD3F7E8FF1E7
That’s not his name? Lol

**Comment by DEMOLITIONDON96** [comment]
> 25217480-055D-45DA-B483-BD3F7E8FF1E7
> That’s not his name? Lol

Bruh, look at the name of who owns the repo, they did absolutely nothing for it, they simply stole SonicProYT’s engine name, and plopped it into their fork, and claimed it as their when they forked my engine

**Pull request closed without merging**
