### PR TITLE
GameJolt Support (WIP)

### PR DESCRIPTION
**Pull request by DEMOLITIONDON96**
Ha ha, Imagine implementing GameJolt API Support?

don't expect this to be merged until at least after a couple of weeks or so lol

### CODE REVIEW

**Comment by Theoyeah** [comment]
mmmmhhh
I plan to do it too for my engine

**Comment by SonicProYT** [comment]
i plan to do this for my kade engine mod too but i can’t get it to work right

**Comment by DEMOLITIONDON96** [comment]
cancelling this idea, not gonna do it after all

**Comment by PrismLight** [comment]
> cancelling this idea, not gonna do it after all

Either because it's too hard, or you don't want people to steal the api and do some random shit to it.

**Comment by DEMOLITIONDON96** [comment]
> > cancelling this idea, not gonna do it after all
> 
> Either because it's too hard, or you don't want people to steal the api and do some random shit to it.

Both, actually

**Comment by Jsa010** [comment]
Demolition: Fails

me: gets it working even w/ leaderboards

but seriously F because it happend to me too

**Pull request closed without merging**
